FROM alpine AS usermaker
RUN addgroup -g 1000 -S group && \
    adduser -u 1000 -S user -G group

FROM ubuntu:18.04
MAINTAINER rodriguezst <github.com/rodriguezst>

COPY tg_downloader.py /app/tg_downloader.py
COPY --from=usermaker /etc/passwd /etc/passwd

RUN apt-get update && apt-get install -y --no-install-recommends \
                                python3 \
                                python3-dev \
                                python3-pip \
                                python3-setuptools \
                                python3-wheel \
                                build-essential \
                && rm -rf /var/lib/apt/lists/* \
                && pip3 install cryptg \
                && pip3 install telethon[cryptg] \
                && apt-get remove --purge -y build-essential \
                                python3-dev \
                && apt autoremove -y \
                && rm -rf /var/lib/apt/lists/* \
                && chmod +x /app/tg_downloader.py \
                && chown user:group /app/tg_downloader.py

USER user
WORKDIR /app
ENTRYPOINT ["/app/tg_downloader.py"]
