#!/bin/bash
curl -L -o manifest-tool-linux-amd64 https://github.com/estesp/manifest-tool/releases/download/v1.0.0-rc/manifest-tool-linux-amd64
chmod +x manifest-tool-linux-amd64
./manifest-tool-linux-amd64 push from-spec manifest.yaml --ignore-missing
